# Multiple Linear Regression
- Dataset: [50_Startups](/AI_ML/machine_learning/datasets/50_Startups.csv)
- Each row has information about the startup and predict the profit that a new start up would generate
- Steps
    - Preprocessing
        - Remove missing values
        - Enocde categorical variables
        - Seperate the target variable from the other independent variables 
    - Split the dataset
    - Train the model
    - Test the model
- Scaling is not performed in linear regression as weights for the individual factors will take care of it

In [1]:
import pandas as pd

df = pd.read_csv("../../../../datasets/50_Startups.csv")
df

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94
5,131876.90,99814.71,362861.36,New York,156991.12
6,134615.46,147198.87,127716.82,California,156122.51
7,130298.13,145530.06,323876.68,Florida,155752.60
8,120542.52,148718.95,311613.29,New York,152211.77
9,123334.88,108679.17,304981.62,California,149759.96


In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     str    
 4   Profit           50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.1 KB


- There are 50 samples and none of have missing values
- The type of State feature is str which is categorical, which has 3 categories i.e. New York, California, Florida
- Thus one hot encoding must be applied on the State variable

In [3]:
df["State"].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

# Seperating the target variable from the other features

In [4]:
X = df.drop(columns = ["Profit"])
y = df["Profit"]
X

,R&D Spend,Administration,Marketing Spend,State
0,165349.20,136897.80,471784.10,New York
1,162597.70,151377.59,443898.53,California
2,153441.51,101145.55,407934.54,Florida
3,144372.41,118671.85,383199.62,New York
4,142107.34,91391.77,366168.42,Florida
5,131876.90,99814.71,362861.36,New York
6,134615.46,147198.87,127716.82,California
7,130298.13,145530.06,323876.68,Florida
8,120542.52,148718.95,311613.29,New York
9,123334.88,108679.17,304981.62,California


# Encoding the categorical variable `State`

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

column_transformer = ColumnTransformer(
    transformers =[("encoder", OneHotEncoder(), ["State"])],
    remainder="passthrough"
)

X = column_transformer.fit_transform(X)
X

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

- The 1st 3 columns is because of the one hot encoding of the state variable
- Since there are 3 possible categories, 3 extra columns are added in the begining and the rest of the columns are retained as it is

# Fetching the columns names after encoding

In [6]:
columns = column_transformer.get_feature_names_out()
print(columns)

# Renaming the columns
renamed_columns = [i.split("__")[1] for i in columns]
print(renamed_columns)

['encoder__State_California' 'encoder__State_Florida'
 'encoder__State_New York' 'remainder__R&D Spend'
 'remainder__Administration' 'remainder__Marketing Spend']
['State_California', 'State_Florida', 'State_New York', 'R&D Spend', 'Administration', 'Marketing Spend']


- The one hot encoded columns will have a prefix of encoder__ and the retained columns will have a prefix of remainder__

# Train test split

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
print(f"Len X_train : {len(X_train)}")
print(f"Len X_test : {len(X_test)}")

Len X_train : 40
Len X_test : 10


# Questions
#### 1. Do we need to drop one of the dummy variable columns to avoid dummy variable trap problem?
- No, because the inbuilt class of linear regression will handle by its own

#### 2. Do we need to find all those features whose P value < significance value ?
- No, the inbuilt class of linear regression will handle by its own


# Training the model

In [8]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X=X_train, y=y_train)


,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


# Predicting on Test Data

In [9]:
y_pred = model.predict(X_test)
y_pred

array([126362.87908251,  84608.45383643,  99677.49425154,  46357.46068583,
       128750.48288497,  50912.41741906, 109741.350327  , 100643.24281644,
        97599.275746  , 113097.42524437])

- We cannot visualize the predictions as we have more than 2 variables, as we have 4 variables we will need a 5D graph to visualize the results
- Analysing the predicted and actual values

In [10]:
results = pd.DataFrame()
results["y_pred"] = y_pred
results["y_true"] = list(y_test)
results

,y_pred,y_true
0,126362.879083,134307.35
1,84608.453836,81005.76
2,99677.494252,99937.59
3,46357.460686,64926.08
4,128750.482885,125370.37
5,50912.417419,35673.41
6,109741.350327,105733.54
7,100643.242816,107404.34
8,97599.275746,97427.84
9,113097.425244,122776.86


### Predict the profit for a startup with R&D Spend = 160000, Administration Spend = 130000, Marketing Spend = 300000 and State = California

In [11]:
sample = pd.DataFrame([[160000, 130000, 300000,"California"]], columns = ["R&D Spend", "Administration", "Marketing Spend", "State"])

model.predict(X=column_transformer.transform(sample))

array([182943.05796893])

# Finding the weights and bias value

In [12]:
model.coef_

array([-3.15260255e+02,  6.23532751e+02, -3.08272495e+02,  8.05630064e-01,
       -6.87878823e-02,  2.98554429e-02])

In [13]:
model.intercept_

np.float64(54343.29984943885)